examen02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls", namespace="home_app")),

]

home/urls.py
from django.urls import path
from home import views
from django.conf import settings

app_name = "home_app"

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('empleados/', views.empleados, name="empleados"),
    path('lider/', views.lider, name="lider"),
    path('actividades/', views.Actividades, name="actividades"),
    path('estado/', views.estadoAct, name="estado"),
    path('reportes/', views.reportes, name="reportes"),
    path('lider_new/', views.lider_registro, name="lider_new"),
    path('empleados_new/', views.empleados_registro, name="empleados_new"),
    path('actividad_new/', views.actividades_registro, name="actividad_new"),
    path('estadoAct_new/', views.tareas_registro_view, name="estadoAct_new"),




]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  </head>
  <body class="container-fluid">
    {% include "nav.html" %}
    <hr class="my-4">
    {% block content %}

    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home_app:inicio' %}">ParraSoft </a>
        <a class="nav-item nav-link active" href="{% url 'home_app:lider' %}">Lideres</a>
        <a class="nav-item nav-link active" href="{% url 'home_app:empleados' %}">Empleados</a>
        <a class="nav-item nav-link active" href="{% url 'home_app:actividades' %}">Actividades</a>
        <a class="nav-item nav-link active" href="{% url 'home_app:estado' %}">Estados de Act</a>
        <a class="nav-item nav-link active" href="{% url 'home_app:reportes' %}">Reportes</a>
        <a class="nav-item nav-link" href="{% url 'home_app:lider_new' %}">Crear Lider</a>
        <a class="nav-item nav-link" href="{% url 'home_app:empleados_new' %}">Crear Empleado</a>
        <a class="nav-item nav-link" href="{% url 'home_app:actividad_new' %}">Crear Actividad</a>
        <a class="nav-item nav-link" href="{% url 'home_app:estadoAct_new' %}">Crear Estado de Actividades</a>
      </div>
      </div>
    </div>
  </nav>
  